org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

# Mod Information
mcversion=26.1.2
mod_id=mangomultiblock
mod_name=MangoMultiblock
mod_named=Mango MultiBlock
mod_license=MIT
mod_version=4.0.0
mod_group_id=nadiendev.mangomultiblock
mod_authors=Mangorage, SrNadien
mod_description=Simple Library mod providing ways of handling multiiblocks
tag_lanzador=NeoForge

# NeoForge Information
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.78
neoversion=26.1.2.78
neoforge_version=26.1.2.78
neoforge_version_range=[26.1.2.78,)
loader_version=[4,)
loader_version_range=[4,)
issue_tracker=

# Neoforge Partchment Subsystems
neogradle.subsystems.parchment.minecraftVersion=1.21.11
neogradle.subsystems.parchment.mappingsVersion=2025.12.20
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
